plugins: rubocop-performance
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
  - '*.gemspec'
  - 'vendor/**/*'
Layout/LineLength:
  Max: 120
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 28
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Metrics/ClassLength:
  Max: 150
  Exclude:
  - 'app/controllers/enumeration/cli_options.rb'
  - 'app/controllers/enumeration/enum_methods.rb'
  - 'app/formatters/sarif.rb'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
  Exclude:
  - 'app/controllers/enumeration/cli_options.rb'
  - 'app/controllers/core/cli_options.rb'
  - 'app/controllers/password_attack.rb'
Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 4
Metrics/PerceivedComplexity:
  Max: 11
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MixinUsage:
  Exclude:
  - 'lib/wpscan/formatter.rb'
Style/NumericPredicate:
  Exclude:
  - 'app/controllers/vuln_api.rb'
