# frozen_string_literal: true

require 'shared_examples/views/vuln_api'
require 'shared_examples/views/wp_version'
require 'shared_examples/views/main_theme'
require 'shared_examples/views/enumeration'
require 'shared_examples/views/core'
require 'shared_examples/views/interesting_findings'
require 'shared_examples/target/platform/wordpress'
require 'shared_examples/target/server/generic'
require 'shared_examples/target/server/apache'
require 'shared_examples/target/server/iis'
require 'shared_examples/target/server/nginx'
require 'shared_examples/finders/wp_items/urls_in_page'
require 'shared_examples/references'
require 'shared_examples/dynamic_finders/wp_items'
require 'shared_examples/browser_actions'
require 'shared_examples/formatter_buffer'
require 'shared_examples/formatter_class_methods'
require 'shared_examples/finding'
require 'shared_examples/independent_finder'
