name: Build Docker Images

on:
  release:
    types: [published]

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set tag to latest
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule'
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Set tag to release name
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "DOCKER_TAG=$RELEASE_TAG_NAME" >> "$GITHUB_ENV"

      - name: Check if DOCKER_TAG is set
        if: env.DOCKER_TAG == ''
        run: |
          echo DOCKER_TAG is not set!
          exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: wpscanteam/wpscan:${{ env.DOCKER_TAG }}
