name: Build Docker Images

on:
  release:
    types: [published]

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set tag to latest
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule'
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Set tag to release name
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Check if DOCKER_TAG is set
        if: env.DOCKER_TAG == ''
        run: |
          echo DOCKER_TAG is not set!
          exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: wpscanteam/wpscan:${{ env.DOCKER_TAG }}
